### ISSUE TITLE
save changes?

### ISSUE THREAD

**Issue by tiagoasousa** [tuckner/automation-capability-matrix#6]
any way to persist changes without export/import? would like the tool to be shared across a team but seems all changes are local?

**Comment by tuckner** [comment]
There is a currently undocumented sharing feature where you can point to a URL containing a configuration (S3 or other file storage) and it will import that config. It will overwrite your current configuration so make sure to export your existing config before visiting.

ex. 
https://automation-capability-matrix.pages.dev/?config=https://drive.google.com/drive/uc?id=1-uKUZykmi_1G6cw8Tyc3-YJx37UDfNcr

At some point I'm hoping to move to a model with accounts and saved data.

Let me know if the url sharing could work for now!

**Comment by tiagoasousa** [comment]
will test ty! but can you share a example config file? the google drive gives a 404 :)

**Comment by tuckner** [comment]
It would just be an export hosted somewhere. Just uploaded one to the new examples directory:

https://automation-capability-matrix.pages.dev/?config=https://raw.githubusercontent.com/tuckner/automation-capability-matrix/main/examples/acm-export.json
